# Footer Info
footer:
  since: 2024

# Side info card
card:
  enable: true
  description: |
    疯疯癫癫，一笑一天
    （笑不出来版）
  iconLinks:
  friendLinks:
    ZhouBlackDuck: https://zhoublackduck.github.io

# Main menu navigation
menu:
  主页:
    name: house
    theme: solid
    link: /
  关于:
    name: id-card
    theme: solid
    link: /about
  归档:
    name: box-archive
    theme: solid
    link: /archives
  目录:
    name: bookmark
    theme: solid
    link: /categories
  标签:
    name: tags
    theme: solid
    link: /tags

# Avatar image
avatar: /images/avatar.png

# Loading image
loading: /images/hertaa_loading.gif

# Home page background image
background:
  - /images/background.png